version: '3.8'
services:
  web:
    image: ${APP_IMAGE_FULL_NAME} # This will be set by our deploy.sh script
    ports:
      - "80:8000"
    environment:
      - NAME=ArunDiv # Keep this or adjust as needed for your app.py
