# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    container_name: devops-flask-app
    ports:
      - "80:8000" # Maps host port 80 to container port 8000 (where Flask app runs)
    restart: always # Ensure the container restarts if it crashes
